---
title: "SSA methods"
author: "Погребников Николай"
output: html_notebook
---

```{r}
afc <- function(filter, omega) {
  k <- seq_along(filter) - 1 #значения от 0 до length(filter) - 1
  h <- function(o) sum(rev(filter) * exp(-k*1i * o))
  abs(sapply(omega, h))
}

freq <- seq(0, pi, 0.001)

filt <- rep(1, 100)
# filt <- c(-1,1)
# filt <- c(-1,2,-1)

omega <- freq/2/pi

plot(afc(filt, freq) ~ omega, type = "l")
```

Построим фильтр из GSSA

```{r}
library(ggplot2)

L <- 81
x <- 1:(L)

filt <- sqrt(sin(pi*x/(L+1))^2)
plot(x, filt)
```

```{r}

L <- 81

freq <- seq(0, pi, 1/1000)

x <- 1:L

filt <- sqrt(sin(pi*x/(L+1))^2)**(1)

omega <- freq/2/pi


plot(afc(filt, freq) ~ omega, type = "l")
```

```{r}
L <- 81
x <- 1:L
alpha <- 5
filt <- sqrt(sin(pi * x / (L + 1))^2)^alpha
sum(filt)
```

```{r fig.width=6, fig.height=12}

for (alpha in c(seq(0, 1, 0.1), seq(1, 20, 2), seq(20, 2000, 50))){
  # Данные для первого графика
  L <- 81
  x <- 1:L
  filt <- sqrt(sin(pi * x / (L + 1))^2)^alpha
  
  # Данные для второго графика
  freq <- seq(0, pi, length.out = 1000)
  omega <- freq / (2 * pi)
  
  
  # Установка двух графиков на одном полотне
  par(mfrow = c(2, 1))  # 1 строка, 2 столбца
  
  # Первый график
  plot(x, filt, type = "l", col = "blue", lwd = 2,
       main = "График filt", xlab = "x", ylab = "filt")
  
  # Второй график
  plot(omega, afc(filt, freq), type = "l", col = "red", lwd = 2,
       main = "График afc", xlab = expression(omega), ylab = "AFC")
  
  # Вернуть настройки по умолчанию (опционально)
  par(mfrow = c(1, 1))
}
```

```{r}
library(magick)

# Папка для временных изображений
dir.create("frames")

# Цикл для создания и сохранения кадров
for (alpha in c(seq(0, 1, 0.1), seq(1, 20, 2), seq(20, 2000, 50))){
  # Данные для первого графика
  L <- 81
  x <- 1:L
  filt <- sqrt(sin(pi * x / (L + 1))^2)^alpha
  
  # Данные для второго графика
  freq <- seq(0, pi, length.out = 1000)
  omega <- freq / (2 * pi)
  
  # Создание файла изображения для текущего кадра
  png(sprintf("frames/frame_%f.png", alpha * 100), width = 800, height = 600)
  par(mfrow = c(2, 1))  # Установка двух графиков на одном полотне
  
  # Первый график
  plot(x, filt, type = "l", col = "blue", lwd = 2,
       main = paste("График filt, alpha = ", alpha), xlab = "x", ylab = "filt")
  
  # Второй график
  plot(omega, afc(filt, freq), type = "l", col = "red", lwd = 2,
       main = "График afc", xlab = expression(omega), ylab = "AFC")
  
  # Закрытие устройства вывода
  dev.off()
}
```

```{r}
# Загрузка изображений и создание анимации
frames <- list.files("frames", full.names = TRUE, pattern = "png")
frames <- sort(frames)  # Дополнительная проверка правильного порядка
images <- image_read(frames)

# Создание GIF
animation <- image_animate(images, fps = 5)  # Установите желаемую частоту кадров

# Сохранение GIF
image_write(animation, "animated_plot.gif")

# Удаление временных файлов
# unlink("frames", recursive = TRUE)
```

### WOSSA

```{r}
library(Rssa)
```

```{r}
ssa
```

```{r}

methods(class = "wossa")


```

```{r}
Rssa:::decompose.wossa
```

```{r}
n <- 96*2-1
x <- 0:(n-1)
L <- 50
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y3 <- exp(x/100) + 1
y <- y1 + y2 + y3
alpha <- 1/2
filt <- sqrt(sin(pi * 1:(L) / (L + 1))^2)^alpha

  
s <- ssa(y, L)
r <- reconstruct(s, groups = list(
  e = c(1),
  s1 = 2:3,
  s2 = 4:5
))

sw <- ssa(y, L, col.oblique = filt, row.oblique = rep(1, n-L+1))
rw <- reconstruct(sw, groups = list(
  e = c(1),
  s1 = 2:3,
  s2 = 4:5
))

mse <- function(f_true, f_reconstructed){
   mean((f_true - f_reconstructed)^2) 
}

mse(r$s2, rw$s2)
mse(r$e, y3)
mse(rw$e, y3)
# mse()

# plot(rw$e)
# lines(y3, col="red")
```

### GSSA

```{r}
library(Rssa)

gssa <- function(ts, L, alpha = 0){
  N <- length(ts)
  tmp <- 1:(L)
  w <- sqrt(sin(pi*tmp/(L+1))^2)**alpha
  X <- diag(w) %*% hankel(ts, L)
  K <- dim(X)[2] 
  X_t <- t(X)
  S <- X %*% X_t
  
  tmp <- eigen(S)
  lambda <- tmp$values
  lambda <- lambda[lambda > 0]
  d <- length(lambda)
  U <- tmp$vectors[, 1:d]
  
  
  get_V_i <- function(i){
    X_t %*% U[, i] / sqrt(lambda[i])
  }
  
  get_X_i <- function(i){
    sqrt(lambda[i]) * as.matrix(U[, i]) %*% t(as.matrix(get_V_i(i)))
  }
  
  X_mats <- lapply(1:d, get_X_i)
  
  create_A_alpha <- function(){
    A <- c()
    for (i in 1:N){
      if (i <= L-1){
        A <- c(A, sum(w[1:i]))
      }
      else if (L <= i & i <= K){
        A <- c(A, sum(w))
      }
      else{
        A <- c(A, sum(w[(i-K+1):L]))
      }
    }
    A
  }
  
  A_alpha <- create_A_alpha()
  
  # A_alpha |> print()
  
  
  mean_w <- function(x){
    sum(x)/A_alpha[length(x)]
  }
  
  diag_averaging_w <- function(A){
    B <- A[nrow(A):1, ] |> Re()
    lapply(split(B, -(row(B) - col(B)) ), mean_w) |> as.numeric()
  }
  
  reconstr_elementary <- function(){
    lapply(X_mats, diag_averaging_w)
  }
  
  r_elem <- reconstr_elementary()
  # r_elem |> print()
  
  return(
    list(
      ts = r_elem,
      lambda = lambda
    )
  )
  
}




# plot(Reduce("+", r_gssa$ts), type="l", lwd =3)
# lines(y, col="red")
```

```{r}
n <- 96*2-1
x <- 0:(n-1)
L <- 50
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y3 <- exp(x/100) + 1
y <- y1 + y2 + y3
alpha <- 1/2
filt <- sqrt(sin(pi * 1:(L) / (L + 1))^2)^alpha

  
s <- ssa(y, L)
r <- reconstruct(s, groups = list(
  e = c(1),
  s1 = 2:3,
  s2 = 4:5
))

sw <- ssa(y, L, col.oblique = filt, row.oblique = rep(1, n-L+1))
rw <- reconstruct(sw, groups = list(
  e = c(1),
  s1 = 2:3,
  s2 = 4:5
))

mse <- function(f_true, f_reconstructed){
   mean((f_true - f_reconstructed)^2) 
}


r_gssa <- gssa(y, L, alpha = alpha)

# mse(rw$e, r_gssa$ts[[1]])
mse(r$e, y3)
mse(rw$e, y3)
mse(r_gssa$ts[[1]], y3)
```

```{r}
n <- 96*2-1
x <- 0:(n-1)
L <- 50
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y3 <- exp(x/100) + 1
y <- y1 + y2 + y3
y<- y1
alpha <- 1/2
filt <- sqrt(sin(pi * 1:(L) / (L + 1))^2)^alpha

  
s <- ssa(y, L)
r <- reconstruct(s, groups = list(
  s1 = 1:2
))

sw <- ssa(y, L, col.oblique = filt, row.oblique = rep(1, n-L+1))
rw <- reconstruct(sw, groups = list(
  s1 = 1:2
))

mse <- function(f_true, f_reconstructed){
   mean((f_true - f_reconstructed)^2) 
}


r_gssa <- gssa(y, L, alpha = alpha)

# mse(rw$e, r_gssa$ts[[1]])
mse(r$s1, y1)
mse(rw$s1, y1)
mse(r_gssa$ts[[1]] + r_gssa$ts[[2]], y1)
```

### SSA/GSSA как фильтры

```{r}
get_middle_point_filters <- function(ts, L, alpha = 0){
  N <- length(ts)
  tmp <- 1:(L)
  w <- sqrt(sin(pi*tmp/(L+1))^2)^alpha
  X <- diag(w) %*% hankel(ts, L)
  K <- dim(X)[2] 
  X_t <- t(X)
  S <- X %*% X_t
  
  tmp <- eigen(S)
  lambda <- tmp$values
  lambda <- lambda[lambda > 0]
  d <- length(lambda)
  U <- tmp$vectors[, 1:d]
  
  weight <- sum(w)
  # print(lambda)
  # weight <- L
  # print(weight)
  
  get_filter_i <- function(i){
    filt <- c()
    u <- U[, i]
    
    get_sum_j <- function(j){
      sm <- 0
      for ( k in 1:(L-abs(j)) ){
        sm <- sm + u[k]*u[k+abs(j)]*w[k]
      }
      sm / weight
    }
    
    lapply( (-(L-1)):(L-1), get_sum_j ) |> unlist()
  }
  
  lapply(1:d, get_filter_i)
  
  
}

```

#### Проверка на свопадение middle filter и GSSA

```{r}
library(stats)


n <- 96*2-1
x <- 0:(n-1)
L <- 48
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y <- y1 + y2 
alpha <- 10


freq <- seq(0, pi, 0.001)
omega <- freq/2/pi

filters <- get_middle_point_filters(y, L, alpha = alpha)
filt <- filters[[1]] + filters[[2]] 

r_gssa <- gssa(y, L, alpha = alpha)


(r_gssa$ts[[1]] + r_gssa$ts[[2]])  |> plot(type = "l")
# y2 |> lines()
filter(y, filter = filt, method = "convolution", sides = 2) |> lines(col = "red")
```

#### sin попадающий в решетку

```{r}
n <- 96*2-1
x <- 0:(n-1)
L <- 48
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y3 <- exp(x/100) + 1
y <- y1 + y2 + y3


freq <- seq(0, pi, 0.001)
omega <- freq/2/pi

filters <- get_middle_point_filters(y1, L, alpha = 0)
filt <- filters[[1]] + filters[[2]]

plot(afc(filt, freq) ~ omega, type = "l")
abline(v = 1/12, col = "red")
```

как видно, все остальные частоты, кроме частоты синуса, гасятся

#### sin не в решетке

```{r}
n <- 96*2
x <- 0:(n-1)
L <- 43
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y3 <- exp(x/100) + 1
y <- y1 + y2 + y3


freq <- seq(0, pi, 0.001)
omega <- freq/2/pi

filters <- get_middle_point_filters(y1, L, alpha = 0)
filt <- filters[[1]] + filters[[2]]

plot(afc(filt, freq) ~ omega, type = "l")
abline(v = 1/12, col = "red")

filters <- get_middle_point_filters(y1, L, alpha = 1)
filt <- filters[[1]] + filters[[2]]

lines(afc(filt, freq) ~ omega, col ="blue")
```

АЧХ не сильно поменялся

#### exp + const

```{r}
n <- 96*2 -1
x <- 0:(n-1)
L <- 48
y1 <- sin(2*pi/12 * x)
y2 <- cos(2*pi/3 * x)/2
y3 <- exp(x/100) + 1
y <- y1 + y2 + y3


freq <- seq(0, pi, 0.001)
omega <- freq/2/pi

filters <- get_middle_point_filters(y3, L, alpha = 1/2)
filt <- filters[[1]] + filters[[2]]

plot(afc(filt, freq) ~ omega, type = "l")
```

Чем выше частота, тем сильнее она гасится
